char solver(int possible_steps[MAX_POSSIBLE_STEPS],
            struct Coordinate position,
            struct Coordinate destination,
            int       int_array[ARRAY_MAX],
            char     char_array[ARRAY_MAX],
            float   float_array[ARRAY_MAX],
            double double_array[ARRAY_MAX],
            int       int_table[MAZE_HEIGHT][MAZE_WIDTH],
            char     char_table[MAZE_HEIGHT][MAZE_WIDTH],
            float   float_table[MAZE_HEIGHT][MAZE_WIDTH],
            double double_table[MAZE_HEIGHT][MAZE_WIDTH],
            FILE *log_file);